In [1]:
import numpy
import pandas

In [2]:
db = pandas.read_csv('salary_data.csv')

In [3]:
db

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [4]:
from sklearn.linear_model import LinearRegression


In [5]:
model = LinearRegression()


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x = db['YearsExperience'].values.reshape(30,1)

In [8]:
y = db['Salary']

In [9]:
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.33, random_state=42)

In [10]:
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.20, random_state=42)

In [11]:
X_train


array([[10.3],
       [ 8.7],
       [ 4. ],
       [ 1.1],
       [ 2.2],
       [ 5.1],
       [ 2.9],
       [ 4.1],
       [ 4. ],
       [ 7.9],
       [ 1.3],
       [ 1.5],
       [ 9. ],
       [ 2. ],
       [ 7.1],
       [ 9.5],
       [ 5.9],
       [10.5],
       [ 6.8],
       [ 3.2],
       [ 3.9],
       [ 4.5],
       [ 6. ],
       [ 3. ]])

In [12]:
y_train

28    122391.0
24    109431.0
12     56957.0
0      39343.0
4      39891.0
16     66029.0
5      56642.0
13     57081.0
11     55794.0
22    101302.0
1      46205.0
2      37731.0
25    105582.0
3      43525.0
21     98273.0
26    116969.0
18     81363.0
29    121872.0
20     91738.0
7      54445.0
10     63218.0
14     61111.0
19     93940.0
6      60150.0
Name: Salary, dtype: float64

In [13]:
model.coef_

AttributeError: 'LinearRegression' object has no attribute 'coef_'

In [14]:
model.fit(X_train,y_tarin)

NameError: name 'y_tarin' is not defined

In [15]:
model.fit(X_train,y_train)

LinearRegression()

In [16]:
model.coef_


array([9423.81532303])

In [17]:
model.predict(X_test)

array([115790.21011287,  71498.27809463, 102596.86866063,  75267.80422384,
        55477.79204548,  60189.69970699])

In [18]:
y_test


27    112635.0
15     67938.0
23    113812.0
17     83088.0
8      64445.0
9      57189.0
Name: Salary, dtype: float64

In [19]:
y_test[1]

KeyError: 1